apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: jadugar
data:
  mapRoles: |
    - rolearn: arn:aws:iam::653470767467:role/eks-worker-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
