apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jadugar
  name: jadugar-deployment
spec:
  replicas: 1  # Number of replicas/instances to run
  selector:
    matchLabels:
      app: jadugar
  template:
    metadata:
      labels:
        app: jadugar
    spec:
      containers:
        - name: jadugar
          image: 653470767467.dkr.ecr.ap-south-1.amazonaws.com/rohan:latest  # Replace with your ECR repository URI and image tag
          ports:
            - containerPort: 3000 # Port on which your React app listens
