apiVersion: v1
kind: Service
metadata:
  namespace: jadugar
  name: jadugar-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 3000
  selector:
    app: jadugar

